name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # IMPORTANT: checkout repo FIRST
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate snake
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Krishx30
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Commit & push to output branch
      - name: Push snake to output branch
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/*"
          message: "Generate snake"
          default_author: github_actions
          new_branch: output
